# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: generic
sudo: required
os: linux
dist: trusty
notifications:
  email: false
script:
  - sudo add-apt-repository -y ppa:staticfloat/juliareleases
  - sudo add-apt-repository -y ppa:staticfloat/julia-deps
  - sudo apt-get update
  - sudo apt-get install julia
  - julia -e 'Pkg.add("Lint")';
  - julia -e 'using Lint'  # loading after precompilation
